### ISSUE TITLE
Dashboard chart title not saved to db

### ISSUE THREAD

**Issue by terencemo** [mcholste/elsa#21]
When a new chart is created in a dashboard, the chart title is not saved to database. Steps to reproduce:
1. Create a dashboard
2. Add Chart
3. Enter Chart Title and other fields
4. Save

elsa web log shows args { 'title' => "Foo Bar"... }, but in database SELECT * from charts ORDER BY id DESC LIMIT 1; shows the newly created record for chart but "title" : null in the options column

**Comment by mcholste** [comment]
This was fixed in your PR for #23 right?

**Comment by terencemo** [comment]
Yeah
