### ISSUE TITLE
Question about UNIQUE KEY for "fields" table

### ISSUE THREAD

**Issue by adepasquale** [mcholste/elsa#4]
Martin,
not sure the Google Code page is still active, so I'm opening [issue 229](https://code.google.com/p/enterprise-log-search-and-archive/issues/detail?id=229) again here.

[As pointed out](https://groups.google.com/forum/#!topic/security-onion/6nXu_vDWI4U) on the Security Onion mailing list I was asking myself if [this documentation](https://code.google.com/p/enterprise-log-search-and-archive/wiki/Documentation#Adding_Parsers) is correct.

Given that the "fields" table has ```UNIQUE KEY `field` (`field`,`field_type`)```, it might happen that the query below fails because the inner subquery returns more than one result:

    INSERT INTO fields_classes_map (class_id, field_id, field_order) VALUES ((SELECT id FROM classes WHERE class="NEWCLASS"), (SELECT id FROM fields WHERE field="dstip"), 7);

Don't you think it would be better to change the unique key to "field" only, or changing the documentation in order to use both "field" and "field_type" in the WHERE clause (like below)?

    INSERT INTO fields_classes_map (class_id, field_id, field_order) VALUES ((SELECT id FROM classes WHERE class="NEWCLASS"), (SELECT id FROM fields WHERE field="dstip" AND field_type="int"), 7);

Thanks,
-- Andrea

**Comment by mcholste** [comment]
Agree, the above commit makes field unique of its own accord.
